### ISSUE TITLE
consolidate Procedures and analytics-standards

### ISSUE THREAD

**Issue by afeld** [18F/analytics#15]
From what I can tell, it seems like these pages have a lot of overlap:

* https://github.com/18F/analytics/blob/master/procedures.md
* https://github.com/18F/analytics-standards

Cool with merging them? Thinking the former into the latter, but whatever y'all think is best.

**Comment by jackiekazil** [comment]
Hey @afeld talked about this during our analytics coworking session. I have it on the to-do list for next week ... that and creating clear distinctions between the repos. Thank you for creating a ticket.... I will update you when we have discussed. (Analytics coworking is at 10am on Mondays, if you want to join.)

**Comment by afeld** [comment]
Thanks for the invite! I'm coming at this with my Documentation Working Group hat on...whatever the group decides is fine with me, so long as it's written down in (only) one place.

Sincerely,
Captain :sparkles: Consolidation :sparkles:

**Comment by gbinal** [comment]
Okay - this should be better.  I've dedupped or transferred most all of the former and renamed it [guild-tasks.md](https://github.com/18F/analytics/blob/master/guild-tasks.md).

@jackiekazil and I talked and we feel that there is still a role to be played by both /analytics and /analytics-standards, but their differences will come into clearer relief as they come along.    

Thanks, @afeld
